
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://johnbfair.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id to track your visitors

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

author: "john b fair"
lang: "en"
title: "{ john b fair }"
favicon: "/img/favicon.ico"
description: "Blog and website of John B Fair, blogging mainly for tech. Opinions expressed are mine."
keywords: "fair, john, johnbfair"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/bg_0.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Whatever life hands you...Stand Up. Suit Up. Show Up."
  - text: "Your character is defined by how you react when the chips are down."

me-img: "/img/soho.png"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

syntax-highlight: True

email-share: True
fb-share: True
twitter-share: True
reddit-share: True
google-plus-share: True
linkedin-share: True
tumblr-share: True
pinterest-share: True
vkontakte-share: True

disqus-shortname: "botanist"

###############
# Life Events #
###############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "current"
    description: "Focused on leveling up as a leader, and growing other leaders along the way"
  - image: "/img/timeline/spidertocat.png"
    date: "2014 - present"
    description: "Created Solution Architect at Quicken Loans, have been leading the team ever since"
  - image: "/img/timeline/baracktocat.jpg"
    date: "2012 - 2014"
    description: "Sr. Software Engineer and eventually Software Architect at Quicken Loans"
  - image: "/img/timeline/spidertocat.png"
    date: "2008 - 2012"
    description: "Sr Software Engineer at Centurion Medical Products"
  - image: "/img/timeline/baracktocat.jpg"
    date: "2007 - 2008"
    description: "Moved back to MI, gave EDS a shot"
  - image: "/img/timeline/spidertocat.png"
    date: "2005 - 2007"
    description: "First programming job at Baytree Bank"
  - image: "/img/timeline/baracktocat.jpg"
    date: "2002 - 2005"
    description: "Learned a ton about the mortgage industry at Wells Fargo"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

##################
# Contact layout #
##################

email: "johnbfair@gmail.com"

##################
# Social Buttons #
##################

social:
#  - title: "facebook"
#    url: "https://facebook.com/"
  - title: "twitter"
    url: "https://twitter.com/johnbfair"
  - title: "github"
    url: "https://github.com/johnbfair"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
#  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README", "CONTRIBUTING", "CONTRIBUTORS", "scripts", "_posts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
